use_frameworks!
platform :ios, '8.0'

target 'RxPersistenceSettings_Example' do
  pod 'RxPersistenceSettings', :path => '../'

  target 'RxPersistenceSettings_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3.2'
    pod 'Nimble'#, '~> 7.3.1'
  end
end
